### ISSUE TITLE
Issues compiling templates with Elixir 1.17.rc0

### ISSUE THREAD

**Issue by elliotb** [akoutmos/mjml_eex#18]
When compiling a project using Elixir 1.17 rc0, the pattern matching from the tokenizer fails to match, giving errors such as the following:

```
== Compilation error in file lib/ogat_app/badges/emails/rejection_template.ex ==
** (CaseClauseError) no case clause matching: {:ok, 1, 14, [], [{:identifier, {1, 3, ~c"first_name"}, :first_name}, {:at_op, {1, 2, nil}, :@}], []}
    (mjml_eex 0.10.0) lib/mjml_eex/tokenizer.ex:60: MjmlEEx.Tokenizer.tokenize/6
    (mjml_eex 0.10.0) lib/utils.ex:46: MjmlEEx.Utils.escape_eex_expressions/1
    (mjml_eex 0.10.0) lib/mjml_eex.ex:228: MjmlEEx.get_raw_template/3
    (mjml_eex 0.10.0) expanding macro: MjmlEEx.__using__/1
 ```

It appears to be caused by :erlang_tokenizer.tokenize/3 now including an extra item in the returned tuple, which was introduced in [this commit](https://github.com/elixir-lang/elixir/commit/d7ea2fa2e4e5de1990297be19495fc93740b2e8b#diff-fcde431bca671a0a2ce2982a276b1475fbe9523badc23b72457dfca9ecfc8e4b).

**Comment by akoutmos** [comment]
Thanks for the heads up! I'll fix this up over the weekend and cut a new release.

**Comment by akoutmos** [comment]
I merged in the PR with the fix. I'm going to test a few things out in my production app before cutting a release though. Look out for a release early next week :).

**Comment by elliotb** [comment]
Thanks!

**Comment by alappe** [comment]
@akoutmos Running into the same issue I just wanted to say my setup works fine with master, so a release would be appreciated :)

**Comment by akoutmos** [comment]
I'm currently having issues with erlexec on my ARM mac:

```
$ mix test
Generated mjml_eex app

09:33:07.207 [notice] Application erlexec exited: :exec_app.start(:normal, []) returned an error: shutdown: failed to start child: :exec
    ** (EXIT) bad return value: ~c"Cannot find file ./_build/test/lib/erlexec/priv/false: no such file or directory"

09:33:07.217 [notice] Application telemetry exited: :stopped

09:33:07.217 [notice] Application phoenix_html exited: :stopped

09:33:07.217 [notice] Application eex exited: :stopped

09:33:07.217 [notice] Application mjml exited: :stopped

09:33:07.217 [notice] Application rustler_precompiled exited: :stopped

09:33:07.217 [notice] Application castore exited: :stopped
** (Mix) Could not start application erlexec: :exec_app.start(:normal, []) returned an error: shutdown: failed to start child: :exec
    ** (EXIT) bad return value: ~c"Cannot find file ./_build/test/lib/erlexec/priv/false: no such file or directory"
```

I'll be cutting a new release after I make a PR back to erlexec fixing this issue.

**Comment by alappe** [comment]
Ah, ok… I don't use that, so trouble on my arm mac. Thanks!

**Comment by akoutmos** [comment]
It only impact users that are using Node compiler as opposed to the mjml NIF. After some more digging cutting a release wouldn't change the fact that this is currently broken for people due to erlexec. Release has been cut!

**Comment by alappe** [comment]
```
Error while loading project :mjml_eex at …/deps/mjml_eex
** (File.Error) could not read file "VERSION": no such file or directory
    (elixir 1.17.0) lib/file.ex:385: File.read!/1
    …/deps/mjml_eex/mix.exs:89: MjmlEEx.MixProject.project_version/0
```

The file is indeed missing in the directory.

**Comment by akoutmos** [comment]
oof. Try it again. I forgot to add the version file to mix.exs package block -_-

**Comment by alappe** [comment]
Works fine, thank you and sorry for rushing you on the release :-/
