### ISSUE TITLE
How to use gettext inside the mjml template?

### ISSUE THREAD

**Issue by drselump14** [akoutmos/mjml_eex#20]
Hi, I'm not familiar with mjml syntax, but I was wondering if it's possible to use gettext inside the template?

**Comment by mrdotb** [comment]
I wanted to do the same today. I could not figure out how to make the gettext macro work directly in the template directly so I ended up passing assigns instead.
```mjml
<mj-section padding-top="0">
  <mj-column>
    <mj-text mj-class="sans" font-weight="bold">
      <%= @hi %>
    </mj-text>

    <mj-text mj-class="display">
      <%= @message %>
    </mj-text>
...
```
```elixir
  defp html_body(customer, action_url) do
    assigns =
      [
        action_url: action_url,
        hi: dgettext("emails", "Hi, %{email}", email: customer.email),
        message: dgettext("emails", "We noticed that you haven't started your free 30-day trial yet."),
        ...
      ]

    render(assigns)
  end
```
Extract and fill the gettext for the locale you support.

Before rendering set the locale in my case i have a locale field on my customer
```elixir
  def new(customer) do
    if customer.locale do
      Gettext.put_locale(DotbWeb.Gettext, customer.locale)
    end

    Email.new(%{
      subject: subject(),
      html_body: html_body(customer, @action_url),
      text_body: text_body(customer, @action_url)
    })
  end
```

The mail in french 
![image](https://github.com/akoutmos/mjml_eex/assets/7212914/57534ac9-8307-4f5b-9dfc-f2f092b6f9d7)

**Comment by akoutmos** [comment]
Good question! In your MJML module, you should be able to `import MyApp.Gettext` (the gettext module that is automatically created with a Phoenix application). Then you can make calls in your MJML template like so: `<%= gettext "Click here" %>` and it should work.

**Comment by akoutmos** [comment]
Added some docs and a test to show how this can be done https://github.com/akoutmos/mjml_eex/commit/faac3a32c5f89843dd7db62ad65d32e45751c7da

Closing this issue for now but lmk if this is insufficient :).

**Comment by drselump14** [comment]
Ah, that's why I received a compilation error when importing the gettext. It should be placed before the 'use' statement. Thank you for the clarification, @akoutmos.
